# declarative/app-of-apps/app-of-apps.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-nginx1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/igyan2013/argocd-test.git
    targetRevision: HEAD
    path: test-nginx1
    helm:
      valueFiles:
        - values.yaml # the main values file
        - values-tag.yaml # this is your extra values file
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
